### ISSUE TITLE
Ubuntu 16.04 - gnome - cannot create notification

### ISSUE THREAD

**Issue by vass-david** [cronvel/libnotify-ffi#1]
Hi. I got this error:

```
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/usr/lib64/libnotify.so'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at fs.readFileSync (fs.js:397:15)
    at new DynamicLibrary (/home/david/Sandbox/bezrealitky/node_modules/libnotify-ffi/node_modules/ffi/lib/dynamic_library.js:67:21)
    at Object.Library (/home/david/Sandbox/bezrealitky/node_modules/libnotify-ffi/node_modules/ffi/lib/library.js:45:12)
    at Object.dl (/home/david/Sandbox/bezrealitky/node_modules/libnotify-ffi/lib/dl.js:238:20)
    at Object.defineProperty.get [as lib] (/home/david/Sandbox/bezrealitky/node_modules/libnotify-ffi/lib/libnotify.js:45:23)
    at Object.init (/home/david/Sandbox/bezrealitky/node_modules/libnotify-ffi/lib/libnotify.js:62:20)
    at Object.createNotification (/home/david/Sandbox/bezrealitky/node_modules/libnotify-ffi/lib/libnotify.js:121:30)
    at Object.<anonymous> (/home/david/Sandbox/bezrealitky/test.js:4:11)
```

My code:

```
const libnotify = require('libnotify-ffi');

libnotify.createNotification({
  summary: 'test',
  body: 'test',
  actions: {
    open: {
      label: 'Open',
      callback: () => {
        console.log('open was clicked');
      },
    },
  },
}).push();
```

**Comment by cronvel** [comment]
Hi, the message is indeed explicit: libnotify.so is not found.
Maybe the lib is not installed on your system, or it is installed elsewhere. 

Also you should give a try to my other package: [freedesktop-notifications](https://www.npmjs.com/package/freedesktop-notifications). It does the same but works differently. Here we rely on a dynamic lib, there we directly use DBus. 

Freedesktop-notifications is more reliable, and has more features. That's the module I use for my own projects.

**Comment by cronvel** [comment]
By the way, if you found out that libnotify.so is installed on another directory on your system, please tell me, I would gladly add that path too.

For instance, only the 2 standard locations are tried:
/usr/lib/libnotify.so
/usr/lib64/libnotify.so

**Comment by diegoaguilar** [comment]
Is this supposed to work after getting `libnotify-bin` package installed?

**Comment by cronvel** [comment]
Your OS?
An error message?
It works as long as libnotify.so is found.
